POST http://localhost:3000/category
Content-Type: application/json

{
  "name": "Electronics",
  "description": "All Electronics",
  "icon": "📱"
}


###
POST http://localhost:3000/category
Content-Type: application/json

{
  "name": "Home & Kitchen",
  "description": "Home and Kitchen",
  "icon": "🏠"
}

###
POST http://localhost:3000/category
Content-Type: application/json

{
  "name": "Fasion & Apparel",
  "description": "Clothes, shoesm accessories and bags",
  "icon": "👕"
}


###
POST http://localhost:3000/category
Content-Type: application/json

{
  "name": "Health & Beauty",
  "description": "Skincare, makeup, grooming and wellness products",
  "icon": "💄"
}



###
POST http://localhost:3000/category
Content-Type: application/json

{
  "name": "Sports & Outdoors",
  "description": "Fitness equipment, camping gear, sportswear and outdoor accessories",
  "icon": "⚽️"
}



###
GET http://localhost:3000/category
Accept: application/json


###
GET http://localhost:3000/category/68fbc4f6fecec83e1747c578
Accept: application/json


###
GET http://localhost:3000/category/by-product-count?min=0&max=10
Accept: application/json


###
GET http://localhost:3000/category/search?q=f
Accept: application/json


###
PATCH http://localhost:3000/category/68f9312f5ffc661505040139
Accept: application/json
Content-Type: application/json

{
  "icon": "🥭"
}


###
DELETE http://localhost:3000/category/68f9312f5ffc661505040139
Accept: application/json
